# packages/hc_dispatcher_actuator.yaml
# Dispatcher V2 Actuator (Setpoint Control)
# Adjusts thermostat setpoints to induce calls instead of toggling switches.
# Safety gates:
# - Requires input_boolean.hc_dispatcher_mode_enabled == on
# - Auto-trigger requires input_boolean.hc_dispatcher_auto_approve == on
# - Min run time enforced before restoring baseline setpoints

automation:
  - id: hc_dispatch_v2_apply_batch
    alias: "HC Dispatch V2 - Apply Batch (Setpoints)"
    mode: queued
    max: 10
    trigger:
      # 1. Auto Mode: Trigger on suggestion change
      - platform: state
        entity_id: sensor.hc_dispatch_suggested_batch
      # 2. Manual Mode Button Press
      - platform: state
        entity_id: input_button.hc_dispatch_approve_batch

    condition:
      # Master Switch must be ON
      - condition: state
        entity_id: input_boolean.hc_dispatcher_mode_enabled
        state: "on"

      # If triggered by sensor change, only proceed if Auto-Approve is ON
      - condition: template
        value_template: >
          {% if trigger.platform == 'state' and trigger.entity_id == 'sensor.hc_dispatch_suggested_batch' %}
            {{ is_state('input_boolean.hc_dispatcher_auto_approve', 'on') }}
          {% else %}
            true
          {% endif %}

    action:
      - variables:
          invalid: ['unknown','unavailable','none','']
          raw_batch: "{{ states('sensor.hc_dispatch_suggested_batch') }}"
          last_batch: "{{ states('input_text.hc_dispatch_last_suggested_batch') }}"
          manual_trigger: "{{ trigger.platform == 'state' and trigger.entity_id == 'input_button.hc_dispatch_approve_batch' }}"
          effective_batch: >
            {% if manual_trigger %}
              {% if raw_batch in invalid or raw_batch == 'idle' %}
                {{ last_batch }}
              {% else %}
                {{ raw_batch }}
              {% endif %}
            {% else %}
              {{ raw_batch }}
            {% endif %}
          # Prefer guardrail final_zones when available; otherwise parse the human string
          batch_zones: >
            {% set ns = namespace(out=[]) %}
            {% set guardrail_zones = state_attr('sensor.hc_dispatch_guardrail','final_zones') %}
            {% if guardrail_zones not in ['none','unknown','unavailable','', None] and raw_batch not in invalid and raw_batch != 'idle' %}
              {% set ns.out = guardrail_zones.split(',') %}
            {% else %}
              {% for z in range(1,10) %}
                 {% if ('Z' ~ z ~ ' ') in effective_batch or ('Z' ~ z ~ '+') in effective_batch or effective_batch.startswith('Z' ~ z) %}
                   {% set ns.out = ns.out + ['z' ~ z] %}
                 {% endif %}
              {% endfor %}
            {% endif %}
            {{ ns.out }}
          min_run_sec: "{{ (states('input_number.hc_dispatch_min_run_minutes')|float(10)) * 60 }}"

      # Avoid acting if the batch is unavailable/unknown
      - condition: template
        value_template: "{{ effective_batch not in ['unknown','unavailable','none',''] }}"

      # 1. Update the "Approved Batch" text helper
      - service: input_text.set_value
        target:
          entity_id: input_text.hc_dispatch_approved_batch
        data:
          value: "{{ effective_batch }}"

      # 2. Iterate all zones and set target/baseline setpoints
      - repeat:
          for_each: ["z1","z2","z3","z4","z5","z6","z7","z8","z9"]
          sequence:
            - variables:
                z: "{{ repeat.item }}"
                should_be_on: "{{ z in batch_zones }}"
                climate_map:
                  z1: climate.z1_first_floor_bedroom_and_bath
                  z2: climate.zone_2_second_floor_office_and_upper_guest
                  z3: climate.zone_3_basement_bath_and_common
                  z4: climate.zone_4_garage
                  z5: climate.zone_5_virtual_thermostat_first_floor_living
                  z6: climate.zone_6_master_thermostat
                  z7: climate.zone_7_basement_bar_and_tv_room_south_side
                  z8: climate.zone_8_dining_room
                  z9: climate.zone_9_basement_bedroom
                climate: "{{ climate_map[z] }}"
                target_temp: "{{ states('input_number.hc_disp_' ~ z ~ '_setpoint_f')|float(0) }}"
                baseline_temp: "{{ states('input_number.hc_disp_' ~ z ~ '_baseline_setpoint_f')|float(0) }}"
                current_temp: "{{ state_attr(climate, 'temperature')|float(0) }}"
                last_on: "{{ states('input_datetime.hc_dispatch_last_on_' ~ z) }}"
                elapsed_sec: >
                  {% if last_on not in ['unknown','unavailable','none',''] %}
                    {{ (as_timestamp(now()) - as_timestamp(last_on)) | float(0) }}
                  {% else %}
                    999999
                  {% endif %}
                allow_restore: "{{ elapsed_sec >= min_run_sec }}"
                desired_temp: >
                  {% if should_be_on %}
                    {{ target_temp }}
                  {% else %}
                    {% if allow_restore %}
                      {{ baseline_temp }}
                    {% else %}
                      {{ target_temp }}
                    {% endif %}
                  {% endif %}

            - condition: template
              value_template: "{{ desired_temp > 0 }}"

            - condition: template
              value_template: "{{ (current_temp | round(2)) != (desired_temp | round(2)) }}"

            - service: climate.set_temperature
              data:
                entity_id: "{{ climate }}"
                temperature: "{{ desired_temp }}"
