# packages/hc_dispatcher_actuator.yaml
# Dispatcher V2 Actuator (Setpoint Control)
# Adjusts thermostat setpoints to induce calls instead of toggling switches.
# Safety gates:
# - Requires input_boolean.hc_dispatcher_mode_enabled == on
# - Auto-trigger requires input_boolean.hc_dispatcher_auto_approve == on
# - Min run time enforced before restoring baseline setpoints

automation:
  - id: hc_dispatch_v2_apply_batch
    alias: "HC Dispatch V2 - Apply Batch (Setpoints)"
    mode: queued
    max: 10
    trigger:
      # 1. Auto Mode: Trigger on suggestion change
      - platform: state
        entity_id: sensor.hc_dispatch_suggested_batch
      # 2. Manual Mode Button Press
      - platform: state
        entity_id: input_button.hc_dispatch_approve_batch
      # 3. Periodic check to enforce min-run restore
      - platform: time_pattern
        minutes: "/1"

    condition:
      # Master Switch must be ON
      - condition: state
        entity_id: input_boolean.hc_dispatcher_mode_enabled
        state: "on"

      # If triggered by sensor change, only proceed if Auto-Approve is ON
      - condition: template
        value_template: >
          {% if trigger.platform == 'state' and trigger.entity_id == 'sensor.hc_dispatch_suggested_batch' %}
            {{ is_state('input_boolean.hc_dispatcher_auto_approve', 'on') }}
          {% else %}
            true
          {% endif %}

    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{ trigger.platform == 'state'
                     and trigger.entity_id == 'input_button.hc_dispatch_approve_batch'
                     and states('sensor.hc_dispatch_suggested_batch') in ['unknown','unavailable','none','','idle'] }}
            sequence:
              - wait_template: >
                  {{ states('sensor.hc_dispatch_suggested_batch') not in ['unknown','unavailable','none','','idle'] }}
                timeout: "00:00:30"
                continue_on_timeout: true

      - variables:
          invalid: ['unknown','unavailable','none','']
          raw_batch: "{{ states('sensor.hc_dispatch_suggested_batch') }}"
          last_batch: "{{ states('input_text.hc_dispatch_last_suggested_batch') }}"
          last_batch_zones_str: "{{ states('input_text.hc_dispatch_last_batch_zones') }}"
          last_batch_zones_list: >
            {% if last_batch_zones_str not in ['none','unknown','unavailable','', None] %}
              {{ last_batch_zones_str.split(',') }}
            {% else %}
              {{ [] }}
            {% endif %}
          manual_trigger: "{{ trigger.platform == 'state' and trigger.entity_id == 'input_button.hc_dispatch_approve_batch' }}"
          live_active: >
            {% set ns = namespace(list=[]) %}
            {% for z in range(1,10) %}
              {% if is_state('binary_sensor.hc_z' ~ z ~ '_call_for_heat','on') %}
                {% set ns.list = ns.list + ['z' ~ z] %}
              {% endif %}
            {% endfor %}
            {{ ns.list }}
          batch_callers_str: "{{ states('input_text.hc_dispatch_batch_callers') }}"
          batch_callers_list: >
            {% if batch_callers_str not in ['none','unknown','unavailable','', None] %}
              {{ batch_callers_str.split(',') }}
            {% else %}
              {{ [] }}
            {% endif %}
          effective_batch: >
            {% if manual_trigger %}
              {% if raw_batch in invalid or raw_batch == 'idle' %}
                {{ last_batch }}
              {% else %}
                {{ raw_batch }}
              {% endif %}
            {% else %}
              {{ raw_batch }}
            {% endif %}
          # Prefer guardrail final_zones when available; otherwise parse the human string
          final_zones_str: >
            {% set guardrail_zones = state_attr('sensor.hc_dispatch_guardrail','final_zones') %}
            {% if guardrail_zones not in ['none','unknown','unavailable','', None] and raw_batch not in invalid and raw_batch != 'idle' %}
              {{ guardrail_zones }}
            {% else %}
              {% set ns = namespace(out=[]) %}
              {% for z in range(1,10) %}
                 {% if ('Z' ~ z ~ ' ') in effective_batch or ('Z' ~ z ~ '+') in effective_batch or effective_batch.startswith('Z' ~ z) %}
                   {% set ns.out = ns.out + ['z' ~ z] %}
                 {% endif %}
              {% endfor %}
              {{ ns.out | join(',') if ns.out|length else 'none' }}
            {% endif %}
          base_zones_str: >
            {% set guardrail_base = state_attr('sensor.hc_dispatch_guardrail','base_zones') %}
            {% if guardrail_base not in ['none','unknown','unavailable','', None] and raw_batch not in invalid and raw_batch != 'idle' %}
              {{ guardrail_base }}
            {% else %}
              {{ final_zones_str }}
            {% endif %}
          final_zones_list: >
            {% if final_zones_str not in ['none','unknown','unavailable','', None] %}
              {{ final_zones_str.split(',') }}
            {% else %}
              {{ [] }}
            {% endif %}
          new_batch_start: >
            {{ final_zones_str not in ['none','unknown','unavailable','', None]
               and last_batch_zones_str in ['none','unknown','unavailable','', None] }}
          new_zones_list: >
            {% set ns = namespace(out=[]) %}
            {% for z in final_zones_list %}
              {% if z not in last_batch_zones_list %}
                {% set ns.out = ns.out + [z] %}
              {% endif %}
            {% endfor %}
            {{ ns.out }}
          base_zones_list: >
            {% if base_zones_str not in ['none','unknown','unavailable','', None] %}
              {{ base_zones_str.split(',') }}
            {% else %}
              {{ [] }}
            {% endif %}
          batch_zones_str: >
            {% if final_zones_str not in ['none','unknown','unavailable','', None] %}
              {{ final_zones_str }}
            {% elif last_batch_zones_str not in ['none','unknown','unavailable','', None] %}
              {{ last_batch_zones_str }}
            {% else %}
              none
            {% endif %}
          batch_zones_list: >
            {% if batch_zones_str not in ['none','unknown','unavailable','', None] %}
              {{ batch_zones_str.split(',') }}
            {% else %}
              {{ [] }}
            {% endif %}
          added_zones_list: >
            {% set ns = namespace(out=[]) %}
            {% for z in final_zones_list %}
              {% if z not in base_zones_list %}
                {% set ns.out = ns.out + [z] %}
              {% endif %}
            {% endfor %}
            {{ ns.out }}
          force_mode: "{{ states('input_select.hc_dispatch_force_mode') }}"
          force_delta: "{{ states('input_number.hc_dispatch_force_delta_f')|float(1.0) }}"
          force_cap: "{{ states('input_number.hc_dispatch_force_cap_f')|float(75) }}"
          min_run_sec: "{{ (states('input_number.hc_dispatch_min_run_minutes')|float(10)) * 60 }}"
          allow_restore_all: >
            {% set ok = true %}
            {% for z in batch_zones_list %}
              {% set last_on = states('input_datetime.hc_dispatch_last_on_' ~ z) %}
              {% if last_on not in ['unknown','unavailable','none',''] %}
                {% set elapsed = (as_timestamp(now()) - as_timestamp(last_on)) | float(0) %}
              {% else %}
                {% set elapsed = 999999 %}
              {% endif %}
              {% if elapsed < min_run_sec %}
                {% set ok = false %}
              {% endif %}
            {% endfor %}
            {{ ok }}
          eff_ok: "{{ 1 if effective_batch not in ['unknown','unavailable','none',''] else 0 }}"

      - service: input_text.set_value
        target:
          entity_id: input_text.hc_dispatch_last_apply_debug
        data:
          value: >
            trg={{ trigger.entity_id }} raw={{ raw_batch }} eff={{ effective_batch }} ok={{ eff_ok }} fz={{ final_zones_str }}

      # Avoid acting if the batch is unavailable/unknown
      - condition: template
        value_template: "{{ eff_ok == 1 }}"

      # 1. Update the "Approved Batch" text helper
      - service: input_text.set_value
        target:
          entity_id: input_text.hc_dispatch_approved_batch
        data:
          value: "{{ effective_batch }}"

      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{ final_zones_str not in ['none','unknown','unavailable','', None]
                     and final_zones_str != last_batch_zones_str }}
            sequence:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ new_batch_start }}"
                    sequence:
                      - service: input_text.set_value
                        target:
                          entity_id: input_text.hc_dispatch_batch_callers
                        data:
                          value: "{{ live_active | join(',') if live_active|length else 'none' }}"

              - service: input_text.set_value
                target:
                  entity_id: input_text.hc_dispatch_last_batch_zones
                data:
                  value: "{{ final_zones_str }}"

              - repeat:
                  for_each: "{{ new_zones_list }}"
                  sequence:
                    - variables:
                        z: "{{ repeat.item }}"
                        climate_map:
                          z1: climate.z1_first_floor_bedroom_and_bath
                          z2: climate.zone_2_second_floor_office_and_upper_guest
                          z3: climate.zone_3_basement_bath_and_common
                          z4: climate.zone_4_garage
                          z5: climate.zone_5_virtual_thermostat_first_floor_living
                          z6: climate.zone_6_master_thermostat
                          z7: climate.zone_7_basement_bar_and_tv_room_south_side
                          z8: climate.zone_8_dining_room
                          z9: climate.zone_9_basement_bedroom
                        climate: "{{ climate_map[z] }}"
                        baseline_now: "{{ state_attr(climate, 'temperature')|float(0) }}"
                    - condition: template
                      value_template: "{{ baseline_now > 0 }}"
                    - service: input_number.set_value
                      target:
                        entity_id: "{{ 'input_number.hc_disp_' ~ z ~ '_baseline_setpoint_f' }}"
                      data:
                        value: "{{ baseline_now }}"
                    - service: input_datetime.set_datetime
                      target:
                        entity_id: "{{ 'input_datetime.hc_dispatch_last_on_' ~ z }}"
                      data:
                        datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

      - service: input_text.set_value
        target:
          entity_id: input_text.hc_dispatch_last_apply_debug
        data:
          value: >
            loop fz={{ final_zones_str }} bz={{ base_zones_str }} eff={{ effective_batch }}

      # 2. Iterate all zones and set target/baseline setpoints
      - repeat:
          for_each: ["z1","z2","z3","z4","z5","z6","z7","z8","z9"]
          sequence:
            - variables:
                z: "{{ repeat.item }}"
                in_batch: "{{ z in batch_zones_list }}"
                should_be_on: "{{ z in final_zones_list }}"
                climate_map:
                  z1: climate.z1_first_floor_bedroom_and_bath
                  z2: climate.zone_2_second_floor_office_and_upper_guest
                  z3: climate.zone_3_basement_bath_and_common
                  z4: climate.zone_4_garage
                  z5: climate.zone_5_virtual_thermostat_first_floor_living
                  z6: climate.zone_6_master_thermostat
                  z7: climate.zone_7_basement_bar_and_tv_room_south_side
                  z8: climate.zone_8_dining_room
                  z9: climate.zone_9_basement_bedroom
                climate: "{{ climate_map[z] }}"
                climate_state: "{{ states(climate) }}"
                target_temp: "{{ states('input_number.hc_disp_' ~ z ~ '_setpoint_f')|float(0) }}"
                baseline_temp: "{{ states('input_number.hc_disp_' ~ z ~ '_baseline_setpoint_f')|float(0) }}"
                current_setpoint: "{{ state_attr(climate, 'temperature')|float(0) }}"
                current_room_temp: "{{ state_attr(climate, 'current_temperature')|float(0) }}"
                last_on: "{{ states('input_datetime.hc_dispatch_last_on_' ~ z) }}"
                elapsed_sec: >
                  {% if last_on not in ['unknown','unavailable','none',''] %}
                    {{ (as_timestamp(now()) - as_timestamp(last_on)) | float(0) }}
                  {% else %}
                    999999
                  {% endif %}
                allow_restore: "{{ elapsed_sec >= min_run_sec }}"
                force_for_zone: >
                  {% if force_mode == 'All' and should_be_on %}
                    true
                  {% elif force_mode == 'Added Only' and should_be_on and (z in added_zones_list) %}
                    true
                  {% else %}
                    false
                  {% endif %}
                desired_temp: >
                  {% if should_be_on %}
                    {% if force_for_zone and current_room_temp > 0 %}
                      {% set v = target_temp if target_temp > (current_room_temp + force_delta) else (current_room_temp + force_delta) %}
                      {{ v if v < force_cap else force_cap }}
                    {% else %}
                      {{ target_temp }}
                    {% endif %}
                  {% else %}
                    {% if allow_restore %}
                      {{ baseline_temp }}
                    {% else %}
                      {{ target_temp }}
                    {% endif %}
                  {% endif %}

            - condition: template
              value_template: "{{ in_batch }}"

            - service: input_text.set_value
              target:
                entity_id: input_text.hc_dispatch_loop_marker
              data:
                value: >
                  z={{ z }} on={{ 1 if should_be_on else 0 }}
                  ct={{ current_room_temp|round(1) }} dt={{ desired_temp|round(1) }}
                  st={{ climate_state }} fz={{ final_zones_str }}

            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ z == 'z7' }}"
                  sequence:
                    - service: input_text.set_value
                      target:
                        entity_id: input_text.hc_dispatch_last_apply_debug
                      data:
                        value: >
                          z7={{ 1 if should_be_on else 0 }}
                          ct={{ current_room_temp|round(1) }} dt={{ desired_temp|round(1) }}
                          fz={{ final_zones_str }}

            - choose:
                - conditions:
                    - condition: template
                      value_template: >
                        {{ climate_state not in ['unknown','unavailable','none','']
                           and desired_temp > 0
                           and (current_setpoint | round(2)) != (desired_temp | round(2)) }}
                  sequence:
                    - service: climate.set_temperature
                      continue_on_error: true
                      data:
                        entity_id: "{{ climate }}"
                        temperature: "{{ desired_temp }}"

      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{ raw_batch in ['idle','unknown','unavailable','none','']
                     and batch_zones_list|length > 0
                     and allow_restore_all }}
            sequence:
              - service: input_text.set_value
                target:
                  entity_id: input_text.hc_dispatch_batch_callers
                data:
                  value: "none"
              - service: input_text.set_value
                target:
                  entity_id: input_text.hc_dispatch_last_batch_zones
                data:
                  value: "none"
