automation:
  - id: hc_dispatch_manual_caps_set_until
    alias: "HC Dispatch Manual Caps Override - Set Until"
    mode: queued
    trigger:
      - platform: state
        entity_id: input_boolean.hc_dispatch_manual_override
        to: "on"
      - platform: state
        entity_id: input_number.hc_dispatch_manual_caps_minutes
    condition:
      - condition: state
        entity_id: input_boolean.hc_dispatch_manual_override
        state: "on"
    action:
      - variables:
          mins: "{{ states('input_number.hc_dispatch_manual_caps_minutes')|int(60) }}"
          until_ts: "{{ as_timestamp(now()) + (mins * 60) }}"
          until_str: "{{ (until_ts | timestamp_local) }}"
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.hc_dispatch_manual_caps_until
        data:
          datetime: "{{ until_str }}"

  - id: hc_dispatch_manual_caps_clear_until
    alias: "HC Dispatch Manual Caps Override - Clear Until"
    mode: queued
    trigger:
      - platform: state
        entity_id: input_boolean.hc_dispatch_manual_override
        to: "off"
    action:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.hc_dispatch_manual_caps_until
        data:
          datetime: "{{ (now() - timedelta(minutes=1)).strftime('%Y-%m-%d %H:%M:%S') }}"

  - id: hc_dispatch_manual_caps_expire
    alias: "HC Dispatch Manual Caps Override - Expire"
    mode: queued
    trigger:
      - platform: time_pattern
        minutes: "/1"
    condition:
      - condition: state
        entity_id: input_boolean.hc_dispatch_manual_override
        state: "on"
      - condition: template
        value_template: >
          {% set until = states('input_datetime.hc_dispatch_manual_caps_until') %}
          {{ until not in ['unknown','unavailable','none',''] and as_timestamp(now()) >= as_timestamp(until) }}
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.hc_dispatch_manual_override
